name: Report a Problem
description: Have you found something that does not work well, is too hard to do or is missing altogether? Please create a Problem Report.
labels: ["Status: Needs triage","Status: Needs confirmation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this problem report! Please [search](https://github.com/FreeCAD/FreeCAD/issues) if a similar issue already exists and check out [how to report issues](https://github.com/FreeCAD/FreeCAD?tab=readme-ov-file#reporting-issues). By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/FreeCAD/FreeCAD/blob/main/CODE_OF_CONDUCT.md).

  - type: dropdown
    id: wb
    attributes:
      label: Workbench affected?
      options:
        - Assembly
        - BIM
        - CAM
        - Core (App, Gui,...)
        - Draft
        - FEM
        - Material
        - Measurement
        - Mesh
        - Part
        - Part Design
        - Sketcher
        - Spreadsheet
        - TechDraw
        - Other (specify in description)
      validations:
        required: true

  - type: textarea
    id: description
    attributes:
      label: Problem description
      description: Describe the problem and how it impacts user experience, workflow, maintainability or performance. You can attach images or log files by clicking this area to highlight it and then dragging files in. To attach a FCStd file, ZIP it first.
      placeholder: Describe your problem briefly.
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to reproduce
      description: If the problem appears to be a bug with the current functionality, provide a test case or recipe that reliably reproduces the issue. Ideally record a macro and attach it.
      placeholder: |
        Steps to reproduce the behavior:
        1. Create new '...'
        2. Go to '...'
        3. Click on '...'
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What is the expected behavior?
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual behavior
      description: A clear and concise description of what actually happens. If applicable, add screenshots to help explain the problem.
      placeholder: What is actually happening?
    validations:
      required: true

  - type: textarea
    id: dev_version
    attributes:
      label: Development version info (safe mode)
      description: Download the latest weekly dev release and try reproducing the issue in safe mode (Help → Restart in Safe Mode). Use the About FreeCAD dialog to copy your full version information and paste it here.
      render: shell
    validations:
      required: true

  - type: textarea
    id: good_version
    attributes:
      label: (Optional) Last known good version
      description: If this is a regression, paste the About FreeCAD info from the last known working version.
      render: shell
